package com.young.metaboliccoach.core.model

enum class CoachTheme {
    SYSTEM,
    DARK,
    HIGH_CONTRAST,
}

enum class GlucoseProviderMode {
    NIGHTSCOUT,
    HEALTH_CONNECT,
    XDRIP_BROADCAST,
    CARESENS_PARTNER,
}

data class CoachSettings(
    val glucoseProviderMode: GlucoseProviderMode,
    val healthConnectGlucoseOriginPackage: String?,
    val glucoseUnit: GlucoseUnit,
    val lowGlucoseThresholdMgDl: Int,
    val targetLowerMgDl: Int,
    val targetUpperMgDl: Int,
    val rapidRiseThresholdMgDlPerMinute: Double,
    val exercisePauseFallRateMgDlPerMinute: Double,
    val staleReadingMinutes: Int,
    val walkingDurationMinutes: Int,
    val stairTargetFloors: Int,
    val dailyStepGoal: Int,
    val dailyFloorGoal: Int,
    val prolongedInactivityMinutes: Int,
    val postMealDelayMinutes: Int,
    val postMealWindowMinutes: Int,
    val reminderCooldownMinutes: Int,
    val snoozeMinutes: Int,
    val maximumNotificationsPerDay: Int,
    val quietHoursStartMinuteOfDay: Int,
    val quietHoursEndMinuteOfDay: Int,
    val workingHoursStartMinuteOfDay: Int,
    val workingHoursEndMinuteOfDay: Int,
    val minimumObservationSamples: Int,
    val minimumTimingBucketSamples: Int,
    val minimumComparableTimingBuckets: Int,
    val interventionTimingBucketMinutes: Int,
    val postMealTimingBucketMinutes: Int,
    val followUpDelayBucketMinutes: Int,
    val baselineGlucoseBandMgDl: Int,
    val interventionFollowUpMinutes: Int,
    val quickActionExpiryMinutes: Int,
    val walkingRemindersEnabled: Boolean,
    val stairRemindersEnabled: Boolean,
    val postMealRemindersEnabled: Boolean,
    val notificationsEnabled: Boolean,
    val theme: CoachTheme,
    val fontScale: Float,
)

object DefaultCoachSettings {
    fun create() = CoachSettings(
        glucoseProviderMode = GlucoseProviderMode.NIGHTSCOUT,
        healthConnectGlucoseOriginPackage = null,
        glucoseUnit = GlucoseUnit.MG_DL,
        lowGlucoseThresholdMgDl = 70,
        targetLowerMgDl = 70,
        targetUpperMgDl = 180,
        rapidRiseThresholdMgDlPerMinute = 2.0,
        exercisePauseFallRateMgDlPerMinute = 2.0,
        staleReadingMinutes = 15,
        walkingDurationMinutes = 10,
        stairTargetFloors = 6,
        dailyStepGoal = 8_000,
        dailyFloorGoal = 10,
        prolongedInactivityMinutes = 60,
        postMealDelayMinutes = 30,
        postMealWindowMinutes = 45,
        reminderCooldownMinutes = 60,
        snoozeMinutes = 15,
        maximumNotificationsPerDay = 6,
        quietHoursStartMinuteOfDay = 22 * 60,
        quietHoursEndMinuteOfDay = 7 * 60,
        workingHoursStartMinuteOfDay = 8 * 60,
        workingHoursEndMinuteOfDay = 18 * 60,
        minimumObservationSamples = 3,
        minimumTimingBucketSamples = 8,
        minimumComparableTimingBuckets = 2,
        interventionTimingBucketMinutes = 5,
        postMealTimingBucketMinutes = 15,
        followUpDelayBucketMinutes = 15,
        baselineGlucoseBandMgDl = 20,
        interventionFollowUpMinutes = 60,
        quickActionExpiryMinutes = 24 * 60,
        walkingRemindersEnabled = true,
        stairRemindersEnabled = true,
        postMealRemindersEnabled = true,
        notificationsEnabled = true,
        theme = CoachTheme.DARK,
        fontScale = 1.0f,
    )
}
